FROM openjdk:17

WORKDIR /usr/src/app

## Using `.jar` build -> Must run `./mvnw clean install` first

COPY ./target/*.jar ./app.jar

COPY ./.env ./.env

ENTRYPOINT ["java", "-jar", "/usr/src/app/app.jar"]

## Using plain copy and run -> Very slow

# COPY ./ ./

# CMD [ "./mvnw", "spring-boot:run" ]